spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/rest-springboot?useSSL=false&serverTimezone=UTC&useTimezone=true
    username: developer
    password: 1234567
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  flyway:
    locations: classpath:db/migration

server:
  error:
    include-exception: false

springdoc:
  swagger-ui:
    use-root-path: true
